import Foundation

/// On-disk state file format. Each agent writes one of these to
/// ~/.agentisland/state/<agent_id>.json
public struct AgentState: Codable, Identifiable, Equatable {
    public enum Status: String, Codable {
        /// Inference / reasoning in progress (no tool action yet).
        case thinking
        /// Executing a tool (shell, edit, etc.).
        case running
        /// Blocked on the user (approval, question, plan review).
        case waiting_input
        /// Session open but no current task.
        case idle
        /// Task complete; surface result and let user dismiss.
        case done
        /// Failure that requires the user's attention.
        case error
    }

    public struct Action: Codable, Identifiable, Equatable {
        public enum Role: String, Codable {
            case approve
            case deny
            case option
            case open
            case dismiss
        }

        public var id: String
        public var label: String
        public var role: Role

        public init(id: String, label: String, role: Role) {
            self.id = id
            self.label = label
            self.role = role
        }
    }

    public var schema: Int
    public var agent_id: String
    public var kind: String
    public var display_name: String
    public var status: Status
    /// Correlates UI replies to a specific prompt or approval request.
    public var request_id: String?
    /// Human-readable activity phase, e.g. "analyzing", "running", "waiting".
    /// If omitted, UI falls back to `status`.
    public var phase_title: String?
    public var task: String?
    /// Optional normalized progress in 0...1. Unknown progress stays nil.
    public var progress: Double?
    public var pid: Int?
    /// PID of an app the user wants to bring to the foreground when they click
    /// this agent in the notch (typically the parent terminal: Terminal.app,
    /// iTerm, Ghostty, etc.). Falls back to `pid` if unset.
    public var focus_pid: Int?
    public var cwd: String?
    public var started_at: Date
    public var updated_at: Date
    public var needs_attention: Bool
    public var tail: [String]
    /// Optional inline actions. The current app uses these as affordances to
    /// focus the owning agent; a future two-way protocol can bind them directly.
    public var actions: [Action]?
    public var ttl_seconds: Int

    public var id: String { agent_id }

    public var isStale: Bool {
        Date().timeIntervalSince(updated_at) > Double(ttl_seconds)
    }

    public init(
        schema: Int = 1,
        agent_id: String,
        kind: String,
        display_name: String,
        status: Status,
        request_id: String? = nil,
        phase_title: String? = nil,
        task: String? = nil,
        progress: Double? = nil,
        pid: Int? = nil,
        focus_pid: Int? = nil,
        cwd: String? = nil,
        started_at: Date = Date(),
        updated_at: Date = Date(),
        needs_attention: Bool = false,
        tail: [String] = [],
        actions: [Action]? = nil,
        ttl_seconds: Int = 60
    ) {
        self.schema = schema
        self.agent_id = agent_id
        self.kind = kind
        self.display_name = display_name
        self.status = status
        self.request_id = request_id
        self.phase_title = phase_title
        self.task = task
        self.progress = progress
        self.pid = pid
        self.focus_pid = focus_pid
        self.cwd = cwd
        self.started_at = started_at
        self.updated_at = updated_at
        self.needs_attention = needs_attention
        self.tail = tail
        self.actions = actions
        self.ttl_seconds = ttl_seconds
    }
}

/// One user response generated by the AgentIsland UI for an agent-owned
/// request. Agents consume these from ~/.agentisland/replies/<agent_id>/.
public struct AgentReply: Codable, Identifiable, Equatable {
    public var schema: Int
    public var reply_id: String
    public var agent_id: String
    public var request_id: String?
    public var action_id: String
    public var action_label: String
    public var role: AgentState.Action.Role
    public var value: String?
    public var created_at: Date

    public var id: String { reply_id }

    public init(
        schema: Int = 1,
        reply_id: String = UUID().uuidString,
        agent_id: String,
        request_id: String? = nil,
        action_id: String,
        action_label: String,
        role: AgentState.Action.Role,
        value: String? = nil,
        created_at: Date = Date()
    ) {
        self.schema = schema
        self.reply_id = reply_id
        self.agent_id = agent_id
        self.request_id = request_id
        self.action_id = action_id
        self.action_label = action_label
        self.role = role
        self.value = value
        self.created_at = created_at
    }
}

public enum AgentStatePaths {
    public static var root: URL {
        let home = FileManager.default.homeDirectoryForCurrentUser
        return home.appendingPathComponent(".agentisland", isDirectory: true)
    }
    public static var stateDir: URL { root.appendingPathComponent("state", isDirectory: true) }
    public static var repliesDir: URL { root.appendingPathComponent("replies", isDirectory: true) }

    public static func ensureDirs() throws {
        try FileManager.default.createDirectory(at: stateDir, withIntermediateDirectories: true)
        try FileManager.default.createDirectory(at: repliesDir, withIntermediateDirectories: true)
    }

    public static func file(for id: String) -> URL {
        stateDir.appendingPathComponent("\(id).json")
    }

    public static func repliesDir(for id: String) -> URL {
        repliesDir.appendingPathComponent(id, isDirectory: true)
    }

    public static func replyFile(agentID: String, replyID: String) -> URL {
        repliesDir(for: agentID).appendingPathComponent("\(replyID).json")
    }
}

public extension JSONEncoder {
    static var agentIsland: JSONEncoder {
        let e = JSONEncoder()
        e.dateEncodingStrategy = .iso8601
        e.outputFormatting = [.prettyPrinted, .sortedKeys]
        return e
    }
}

public extension JSONDecoder {
    static var agentIsland: JSONDecoder {
        let d = JSONDecoder()
        d.dateDecodingStrategy = .iso8601
        return d
    }
}

/// Atomic load/save helpers.
public enum AgentStateIO {
    public static func load(id: String) -> AgentState? {
        let url = AgentStatePaths.file(for: id)
        guard let data = try? Data(contentsOf: url) else { return nil }
        return try? JSONDecoder.agentIsland.decode(AgentState.self, from: data)
    }

    public static func save(_ state: AgentState) throws {
        try AgentStatePaths.ensureDirs()
        let url = AgentStatePaths.file(for: state.agent_id)
        let tmp = url.appendingPathExtension("tmp")
        let data = try JSONEncoder.agentIsland.encode(state)
        try data.write(to: tmp, options: .atomic)
        if FileManager.default.fileExists(atPath: url.path) {
            _ = try FileManager.default.replaceItemAt(url, withItemAt: tmp)
        } else {
            try FileManager.default.moveItem(at: tmp, to: url)
        }
    }

    public static func delete(id: String) {
        try? FileManager.default.removeItem(at: AgentStatePaths.file(for: id))
    }

    public static func listAll() -> [AgentState] {
        let dir = AgentStatePaths.stateDir
        guard let files = try? FileManager.default.contentsOfDirectory(at: dir, includingPropertiesForKeys: nil) else {
            return []
        }
        var out: [AgentState] = []
        for f in files where f.pathExtension == "json" {
            if let data = try? Data(contentsOf: f),
               let s = try? JSONDecoder.agentIsland.decode(AgentState.self, from: data) {
                out.append(s)
            }
        }
        return out.sorted { $0.started_at < $1.started_at }
    }
}

public enum AgentReplyIO {
    public static func save(_ reply: AgentReply) throws {
        try AgentStatePaths.ensureDirs()
        let dir = AgentStatePaths.repliesDir(for: reply.agent_id)
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        let url = AgentStatePaths.replyFile(agentID: reply.agent_id, replyID: reply.reply_id)
        let tmp = url.appendingPathExtension("tmp")
        let data = try JSONEncoder.agentIsland.encode(reply)
        try data.write(to: tmp, options: .atomic)
        if FileManager.default.fileExists(atPath: url.path) {
            _ = try FileManager.default.replaceItemAt(url, withItemAt: tmp)
        } else {
            try FileManager.default.moveItem(at: tmp, to: url)
        }
    }

    public static func list(agentID: String, requestID: String? = nil) -> [AgentReply] {
        let dir = AgentStatePaths.repliesDir(for: agentID)
        guard let files = try? FileManager.default.contentsOfDirectory(at: dir, includingPropertiesForKeys: nil) else {
            return []
        }
        return files.compactMap { file in
            guard file.pathExtension == "json",
                  let data = try? Data(contentsOf: file),
                  let reply = try? JSONDecoder.agentIsland.decode(AgentReply.self, from: data) else {
                return nil
            }
            if let requestID, reply.request_id != requestID { return nil }
            return reply
        }
        .sorted { $0.created_at < $1.created_at }
    }

    public static func takeFirst(agentID: String, requestID: String? = nil) -> AgentReply? {
        guard let reply = list(agentID: agentID, requestID: requestID).first else { return nil }
        try? FileManager.default.removeItem(
            at: AgentStatePaths.replyFile(agentID: reply.agent_id, replyID: reply.reply_id)
        )
        return reply
    }

    public static func wait(agentID: String, requestID: String? = nil, timeout: TimeInterval) -> AgentReply? {
        let deadline = Date().addingTimeInterval(timeout)
        repeat {
            if let reply = takeFirst(agentID: agentID, requestID: requestID) {
                return reply
            }
            Thread.sleep(forTimeInterval: 0.2)
        } while Date() < deadline
        return nil
    }
}
